spring:
    mail:
        host: smtp.gmail.com
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: 'Sample@hanuritien.com'
        password: 'Sample'

logging:
  level:
    root: DEBUG
